version: "3.9"
services:
  nodejs:
    container_name: learnmylife_web_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    # image: node:16-bullseye-slim
    volumes:
    - "./backend:/src"
    - /src/node_modules/bcrypt/
    ports:
      - "4600:4600"
    networks:
      - learnmylife-network 
      
    restart: unless-stopped
  # learnmylife_web:
  learnmylife_web:
    container_name: learnmylife_web_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3388:3388
    env_file: ./frontend/.env
    
networks:
  learnmylife-network:
    driver: bridge